const products = [
	{
		_id: '1',
		name: 'Floe Lake',
		image: '/images/placeholder.jpg',
		description: 'Captured in the crisp mountain air of BC',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '89.99',
		countInStock: 3,
		rating: 5,
		numReviews: 4,
	},
	{
		_id: '2',
		name: 'Winnipeg',
		image: '/images/placeholder1.jpg',
		description: 'Along the banks of the Red River',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '99.99',
		countInStock: 5,
		rating: 4.5,
		numReviews: 2,
	},
	{
		_id: '3',
		name: 'Black Lake',
		image: '/images/placeholder2.jpg',
		description: 'Along the ancient mountains of Nopiming',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '79.99',
		countInStock: 1,
		rating: 4.5,
		numReviews: 1,
	},
	{
		_id: '4',
		name: 'McGillvray Falls',
		image: '/images/placeholder3.png',
		description: 'Overlooking an autumn valley',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '109.99',
		countInStock: 3,
		rating: 5,
		numReviews: 4,
	},
	{
		_id: '5',
		name: 'Floe Lake 2',
		image: '/images/placeholder4.jpg',
		description: 'Captured in the crisp mountain air of BC',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '69.99',
		countInStock: '1',
		rating: 4.5,
		numReviews: 4,
	},
	{
		_id: '6',
		name: 'Black Lake',
		image: '/images/placeholder5.jpg',
		description: 'Along the banks of Black Lake',
		category: 'Landscape',
		takenOn: 'Nikon D5300',
		price: '129.99',
		countInStock: 3,
		rating: 5,
		numReviews: 1,
	},
];

export default products;
